---
name: CMake
env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: ${{ matrix.platform.job-name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            {
              job-name: Windows Build - Debug,
              runs-on: windows-latest,
              vcpkg-dir: "C:\\vcpkg",
              cmake-preset: win-debug,
            },
            {
              job-name: Linux Build - Debug,
              runs-on: ubuntu-latest,
              vcpkg-dir: "/usr/local/share/vcpkg",
              cmake-preset: linux-debug,
            },
            {
              job-name: Windows Build - Release,
              runs-on: windows-latest,
              vcpkg-dir: "C:\\vcpkg",
              cmake-preset: win-release,
            },
            {
              job-name: Linux Build - Release,
              runs-on: ubuntu-latest,
              vcpkg-dir: "/usr/local/share/vcpkg",
              cmake-preset: linux-release,
            },
          ]

    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@v3.23.0

      - name: Configure
        run: cmake --preset ${{ matrix.platform.cmake-preset }} -DCMAKE_TOOLCHAIN_FILE=${{ matrix.platform.vcpkg-dir }}/scripts/buildsystems/vcpkg.cmake ${{ github.workspace }}

      - name: Build
        run: cmake --build --preset ${{ matrix.platform.cmake-preset }} ${{github.workspace}}

      - name: Test
        working-directory: ${{github.workspace}}
        run: ctest --preset ${{ matrix.platform.cmake-preset }}

      - name: Install
        working-directory: ${{github.workspace}}
        run: cmake --build --preset ${{ matrix.platform.cmake-preset }} --target install

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.cmake-preset  }}
          path: ${{ github.workspace }}/out/install/${{ matrix.platform.cmake-preset }}

  package:
    name: Package ${{ matrix.platform.friendly-name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            {
              friendly-name: Linux,
              cmake-prefix: linux,
              nuspec: .\scripts\linux.nuspec,
            },
            {
              friendly-name: Windows,
              cmake-prefix: win,
              nuspec: .\scripts\windows.nuspec,
            },
          ]

    runs-on: ubuntu-latest
    needs: build

    permissions:
      packages: write
      actions: write

    steps:
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Get Debug
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.platform.cmake-prefix }}-debug
          path: ${{ github.workspace }}/out/install/${{ matrix.platform.cmake-prefix }}-debug

      - name: Get Release
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.platform.cmake-prefix }}-release
          path: ${{ github.workspace }}/out/install/${{ matrix.platform.cmake-prefix }}-release

      - name: Nuget Pack
        working-directory: ${{github.workspace}}
        run: nuget pack ${{ matrix.platform.nuspec }}
