name: CMake
env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    name: ${{ matrix.platform.job-name }}

    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

    strategy:
      fail-fast: false
      matrix:
        platform: [
          { 
            job-name: Windows Build,
            runs-on: windows-latest,
            vcpkg-dir: "C:\\vcpkg",
            cmake-preset: win-release,
            mono: ""
          },
          { 
            job-name: Linux Build,
            runs-on: ubuntu-latest,
            vcpkg-dir: "/usr/local/share/vcpkg",
            cmake-preset: linux-release,
            mono: mono
          }
        ]

    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@v3.23.0

      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        # Replace <OWNER> with your organization name
        run: >
          ${{ matrix.platform.mono }} `${{ matrix.platform.vcpkg-dir }}/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/Chris-Barton/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "Chris-Barton"
          -password "${{ secrets.ACCESS_TOKEN }}"

      - name: Configure
        run: cmake --preset ${{ matrix.platform.cmake-preset }} -DCMAKE_TOOLCHAIN_FILE=${{ matrix.platform.vcpkg-dir }}/scripts/buildsystems/vcpkg.cmake ${{github.workspace}}

      - name: Build
        run: cmake --build --preset ${{ matrix.platform.cmake-preset }} ${{github.workspace}}

      - name: Test
        working-directory: ${{github.workspace}}
        run: ctest --preset ${{ matrix.platform.cmake-preset  }}
